// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi0u7x1_B5C5G_ry9lNSWVbgKLBZX6rGg',
    appId: '1:203554695406:web:4afa6bbeb3b155df1cebff',
    messagingSenderId: '203554695406',
    projectId: 'stremit-e3c16',
    authDomain: 'stremit-e3c16.firebaseapp.com',
    storageBucket: 'stremit-e3c16.appspot.com',
    measurementId: 'G-15G1N6QFNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpRyrCa2fwWLQgN6JCUELdoD1GZg6bBZ4',
    appId: '1:203554695406:android:f89e1eb3e466a6ef1cebff',
    messagingSenderId: '203554695406',
    projectId: 'stremit-e3c16',
    storageBucket: 'stremit-e3c16.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5CQaa8dLIVzG8fL6IJFQyBEDDIVYWHQ4',
    appId: '1:203554695406:ios:3c5747aa693d7d711cebff',
    messagingSenderId: '203554695406',
    projectId: 'stremit-e3c16',
    storageBucket: 'stremit-e3c16.appspot.com',
    iosBundleId: 'com.example.streamt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5CQaa8dLIVzG8fL6IJFQyBEDDIVYWHQ4',
    appId: '1:203554695406:ios:3c5747aa693d7d711cebff',
    messagingSenderId: '203554695406',
    projectId: 'stremit-e3c16',
    storageBucket: 'stremit-e3c16.appspot.com',
    iosBundleId: 'com.example.streamt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi0u7x1_B5C5G_ry9lNSWVbgKLBZX6rGg',
    appId: '1:203554695406:web:4e1dbd907b3065c11cebff',
    messagingSenderId: '203554695406',
    projectId: 'stremit-e3c16',
    authDomain: 'stremit-e3c16.firebaseapp.com',
    storageBucket: 'stremit-e3c16.appspot.com',
    measurementId: 'G-937T8QDY9R',
  );
}
